"""new fields in user model

Revision ID: 313115430b64
Revises: aa99d87ac545
Create Date: 2021-03-13 11:42:56.224717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313115430b64'
down_revision = 'aa99d87ac545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
